### PR TITLE
Add a Spock stack template

### PR DESCRIPTION
**Pull request by jturner**
Add a new template for the lightweight Haskell web framework,
Spock.

### CODE REVIEW

**Comment by jturner** [comment]
Sorry for the multiple commits, still figuring out stack and how all the config files work together.

**Comment by jturner** [comment]
ping

**Comment by bitemyapp** [comment]
Looks fine to me, so I've merged this.

I'd like to reiterate that I think it'd be a good idea if users could use Stack templates via URIs or if they could download them to their `~/.stack` themselves. Has anything like that happened yet @mgsloan?

**Comment by bitemyapp** [comment]
The merge broke the build? :grimacing:

**Comment by bitemyapp** [comment]
@jturner is this:

```yaml
- location:
    git: "https://github.com/agrafix/Spock.git"
    commit: "HEAD"
  subdirs:
    - Spock
    - Spock-core
    - reroute
```

Strictly necessary? I think the incompatible lts snapshot is breaking it.

**Comment by jturner** [comment]
I believe it is needed and in the recent commit I did exclude it in the test-templates
"spock" : -- contains a stack file, makes `stack new` choke

**Comment by jturner** [comment]
I think it's because lts-7.1 now required haskell 8.0.1 but the CI install haskell 7.10.3 still?

**Comment by bitemyapp** [comment]
Oh this isn't even on you, that's the chrisdone build. I'll wait and see if others pipe up.

**Comment by agrafix** [comment]
@bitemyapp it's not strictly necessary as all the Spock packages are in LTS7 and nightly

**Comment by bitemyapp** [comment]
@agrafix given that, I'd rather remove the custom-ness from the template. @jturner do you have any objections?

**Comment by jturner** [comment]
I do not. I'll work on an updated PR.

**Comment by jturner** [comment]
New PR: https://github.com/commercialhaskell/stack-templates/pull/75

**Pull request merged**
