### PR TITLE
franklinchen's template but with GPL v3 license

### PR DESCRIPTION
**Pull request by vu3rdd**
This template adds a template with hspec and GPLv3 license.

### CODE REVIEW

**Comment by vu3rdd** [comment]
Is there anything else I need to do to get this PR reviewed/merged? I think a lot of people in the community prefers GPL for their projects and it may be useful to provide such an option.

**Comment by bitemyapp** [comment]
I think if we multiply the templates in the repo by everyone's license preference, this'll get a bit silly.

I'd like to put forth that this is a good use-case for supporting user defined, local Stack templates for which I believe there's already an issue.

/cc @mgsloan

**Comment by mgsloan** [comment]
Indeed, see this issue https://github.com/commercialhaskell/stack-templates/issues/55 - we aren't sure what should be templates.  I think we either need:

1) Composable templates.  Is it worth the effort of making this system?  It might be worth it if they can also be used as refactorings.  Like "switch to gpl3" or "add hspec test".

2) Just have a few basic templates.  This is the direction I'm leaning, though a full blown refactoring solution would be really cool.

**Comment by vu3rdd** [comment]
Thanks @mgsloan. That seem like a good direction to take.  The Debian project ships as part of its base-files package, all the common licenses in /usr/share/common-licenses and then package managers are encouraged to refer to it (unless they use a custom license) in the copyright file. I think your idea 2 is a good direction as idea 1 is a lot more effort.

I think stack should not encourage a particular license by putting a default one. Instead it should complain if it finds the boiler plate and ask the user to fill something in there.

**Comment by lwm** [comment]
Closing this off for now based on https://github.com/commercialhaskell/stack-templates/pull/67#issuecomment-240469444.

**Pull request closed without merging**
