### PR TITLE
Fix test for yesod-mongodb template

### PR DESCRIPTION
**Pull request by dfordivam**

### CODE REVIEW

**Comment by dfordivam** [comment]
I am not sure whether the db should be cleared at the start of

**Comment by dfordivam** [comment]
I am not sure whether it is better to clear the db before the tests start. That way the single object pattern match will ensure we have only a single entry matching the message.

**Comment by snoyberg** [comment]
Can you open this on the mongo branch of https://github.com/yesodweb/yesod-scaffold?

**Comment by dfordivam** [comment]
Done. Closing this pull request.

**Pull request closed without merging**
