### PR TITLE
Update Haskeleton

### PR DESCRIPTION
**Pull request by tfausak**
The big change here is switching to use [hpack](https://github.com/sol/hpack)'s `package.yaml` instead of `{{ name }}.cabal`.

### CODE REVIEW

**Comment by mgsloan** [comment]
I'm not sure if it's a good idea to have hpack-only templates yet (except for the explicitly hpack ones like `simple-hpack`).  Should probably wait a few months after `stack new` works with hpack files.

**Comment by tfausak** [comment]
That's a good point. hpack support has been in Stack for less than a month. 

Instead of creating an entire new repo, I could commit these changes to `haskeleton-hpack.hsfiles` or something. That way `stack new haskeleton` continues to work as-is, and you can opt into hpack if you want it. How does that sound?

**Comment by mgsloan** [comment]
Sure!  Alternatively, have both an hpack file and the generated cabal file in the `haskeleton` template

**Comment by tfausak** [comment]
Oh, right. I like that idea best.

**Comment by tfausak** [comment]
I updated this pull request to include the generated Cabal file.

**Comment by tfausak** [comment]
This is ready to go as far as I'm concerned.

**Comment by mgsloan** [comment]
Thanks!

**Pull request merged**
