### PR TITLE
create template-info.yaml

### PR DESCRIPTION
**Pull request by narrative**
As suggested [here](https://github.com/commercialhaskell/stack/issues/1571) and in support of stack pull request [#1988](https://github.com/commercialhaskell/stack/pull/1988).

### CODE REVIEW

**Comment by 3noch** [comment]
Shouldn't the descriptions be part of the template itself? This seems like recipe for confusion, having to do the mapping manually.

**Comment by narrative** [comment]
It would be nice to have the descriptions as part of the template files themselves, but would that not require downloading and parsing every template file, every time a user runs `stack templates`? Granted, they're small files, but I don't see that as being very desirable.

**Comment by 3noch** [comment]
I guess I assumed `stack` already did download all the templates anyway. I don't actually know either way.

**Comment by mgsloan** [comment]
Yeah, cloning the template repo would be sensible for many reasons - https://github.com/commercialhaskell/stack/issues/1595.

I don't see much of a problem with having a metadata file like this, though.  It might make things clearer if something like template inheritance gets added https://github.com/commercialhaskell/stack/issues/1994

**Comment by 3noch** [comment]
@mgsloan You have a much better sense of what's good in this case. I just like to keep things DRY and having to join these two "tables" adds complexity.

**Comment by mgsloan** [comment]
@3noch Yeah, the main issue with adding it to the template itself is that it'd be best to have compatibility with older stack versions.  So either way, we'll need to add new files.  We can either have a template-info file like this, or add a description file per template.

**Comment by 3noch** [comment]
> it'd be best to have compatibility with older stack versions.

@mgsloan For how young stack is, this requirement seems a bit hard to believe (again, you know better than I). I would imagine that `stack`'ss adoption rate is very good too.

**Comment by mgsloan** [comment]
We can't just silently make `stack new` fail for old stack versions.  There is no "template repo version check".  So our only option would be to make a new repo or a subdir or something.

**Comment by 3noch** [comment]
> There is no "template repo version check". So our only option would be to make a new repo or a subdir or something.

Hmm...perhaps that's the main problem? Without any way to describe changes, you can't safely make any!

**Comment by mgsloan** [comment]
Yes, something like that would be good for our various sources of data.  PRs appreciated

**Comment by narrative** [comment]
As discussed [here](https://github.com/commercialhaskell/stack/pull/1988), testing will now fail if there is any discrepancy between templates listed in `template-info.yaml` and the actual templates present in the repository.

**Comment by 3noch** [comment]
@narrative Now *that* is a good idea!

**Comment by mgsloan** [comment]
Oops, forgot to merge this after the stack changes got merged.

**Pull request merged**
