### PR TITLE
Servant testing

### PR DESCRIPTION
**Pull request by algas**
Add hspec testing for servant

### CODE REVIEW

**Comment by lwm** [comment]
Hmmmm, I don't think everyone uses Hspec. It's just not generic enough. People who are using Tasty would have to remove this stuff. Thanks though :+1:

**Comment by bitemyapp** [comment]
@lwm I'm a bit vexed, you want to include more content in the repository but you rejected something that would've been almost strictly helpful for people starting out with Servant. Not everyone uses Hspec but _most_ Haskellers I know *do* use Hspec. There were no tests for this scaffold prior to this PR.

**Comment by bitemyapp** [comment]
@lwm how are you merging these? I usually prefer to use the merge button on the PRs so that attribution is solely to the author and so there's a revert button if someone needs it.

**Comment by lwm** [comment]
@bitemyapp on the command line. The git log shows sole attribution, it's only the Github UI that does the 'with X' stuff. Can big green button from now on if you would prefer.

**Comment by algas** [comment]
Thanks @bitemyapp and @lwm

**Pull request closed without merging**
