### PR TITLE
add travis CI

### PR DESCRIPTION
**Pull request by soenkehahn**
I thought it would be nice to have CI for this repo. There are some templates that fail for different reasons. They are excluded from testing.

### CODE REVIEW

**Comment by mgsloan** [comment]
Thanks!

**Comment by soenkehahn** [comment]
@mgsloan: Can you also enable travis for this repo? I think given my github permissions I can't do that.

**Comment by snoyberg** [comment]
I've just enabled it, thanks :)

**Comment by soenkehahn** [comment]
Great. Thanks for merging!

**Pull request merged**
