### PR TITLE
Add franklinchen template.

### PR DESCRIPTION
**Pull request by FranklinChen**
My template that includes

- Travis setup (using Stack) and badge for README.
- hspec with auto-discovery and QuickCheck.

### CODE REVIEW

**Comment by 3noch** [comment]
Seems like this template deserves a more "semantic" name than just someone's name.

**Comment by snoyberg** [comment]
It's a good point. I merged since we have no standard in place yet about
what making should look like (or frankly any other quality standards for
this repo), but now is probably the right time to kick off a discussion
about what that should look like.

**Comment by FranklinChen** [comment]
Yeah, in the long run it would be cool to create an actual semantics, maybe even provide a UI for choosing desired test frameworks, directory layouts, etc. And that could get complicated really fast, as in the JavaScript world that is full of choices.

**Comment by bitemyapp** [comment]
@FranklinChen composition of raw templates is mostly a no-go AFAICT, which is partly why you see template inheritance so much (Django, Jinja2, etc.)

We'd have to identify capacities/facilities a particular template sub-component could provide (testing, layout, etc.), break them out into explicit datatypes as holes that can be optionally filled, but then throw an error when two resources/components conflict on a particular resource (one wants QuickCheck, one wants HSpec. Mark AppendOk?)

This seems like it could scope-creep badly. There's an appeal to the relatively simple setup that currently exists and I'd tend to favor being opinionated and "just pick something" over trying to combine template components.

Accordingly, seems like the best we could do with such a UI is let people filter by tags (includes HSpec, includes benchmarks, PostgreSQL example)

**Pull request merged**
