### PR TITLE
Add Scotty "hello world" template

### PR DESCRIPTION
**Pull request by laser**
This template provides a _very_ basic Scotty application skeleton. The code in `Main` has been cribbed from the [Scotty documentation](https://hackage.haskell.org/package/scotty) on Hackage.

### CODE REVIEW

**Comment by bitemyapp** [comment]
@laser Seems good to me. Not to be a pest, but I've found it to be best practice to split out a library from my web applications for the test suite and the like. Would that be "too much" for this template or otherwise not to your taste?

**Comment by laser** [comment]
@bitemyapp - 

My intent was to limit the number of files produced by this template - but I have no problem splitting things up a little. Does something like:
```
.
├── app
│   └── Main.hs
├── stuff.cabal
├── src
│   └── Lib.hs
├── stack.yaml
```

...align with what you were thinking?

**Comment by bitemyapp** [comment]
@laser more or less, but this template would probably benefit from less noise anyway. It'll match the Scotty example better with only a `Main.hs` anyway.

**Comment by laser** [comment]
@bitemyapp - Sounds good. Thanks for reviewing. Anything further to do on this branch, then (on my end)?

**Comment by bitemyapp** [comment]
@laser probably not, but do you know why the gitignore files never have terminal newlines? Drives me nuts.

**Comment by snoyberg** [comment]
Thanks for the code and the review!

**Pull request merged**
