### PR TITLE
added servant-0.4 template

### PR DESCRIPTION
**Pull request by soenkehahn**
This PR adds a slightly bigger template for `servant-0.4`.

I put it in a subdirectory, because I thought it would make sense to start to organize the templates a bit, but I don't know if this'll actually work with `stack new`. I can move it to the root dir, of course.

### CODE REVIEW

**Comment by mgsloan** [comment]
I'll merge it and see if it works.

**Comment by prikhi** [comment]
Related: I've created a servant-postgresql template for servant 0.5 & was wondering about a couple things:

* Would this be accepted? Are there some sort of minimum requirements for new templates or will you accept anything useful & working? Is there a limit to how indepth a template can be(maybe that's more an on individual basis)?
* Is there a way to compose templates? So this template & my template could reuse the Test file instead of having to duplicate the code? 
* Is there some sort of style guide for the final app? For instance, when specifying the executable, should Main.hs live in `app/` or `bin/` or `exe/` or something else?
* Is there a way to get stack to add `servant-0.5` & `servant-server-0.5` to the `extra-deps` in `stack.yml` when generating the app? Or should I rely on the cabal file & expect people to add `--solver` to their `stack new` command?

I will make a separate PR when I have some extra time.

**Comment by soenkehahn** [comment]
@mgsloan: I've put the file in the root directory. I've also renamed it to indicate that it uses `hspec-wai-json`.

@prikhi: See a related discussion here: https://groups.google.com/d/topic/haskell-stack/sOI5rY28G3E/discussion

**Comment by mgsloan** [comment]
@prikhi Not really the best place to discuss, I have opened a few issues:

https://github.com/commercialhaskell/stack-templates/issues/55
https://github.com/commercialhaskell/stack/issues/1994
https://github.com/commercialhaskell/stack-templates/issues/56

**Comment by mgsloan** [comment]
I'd really prefer a short name.  Imagine someone typing this in!  We do not have shell autocompletion of template names yet.  `servant` or `servant-0.4` is fine.

I'm actually on the wall as to whether it's useful to have templates for specific libraries like this, as described in https://github.com/commercialhaskell/stack-templates/issues/55 .  I really don't want to start seeing `lens-aeson-hspec-containers` templates.

In the meantime I'm happy to merge very library specific templates, but the policy may change.  I don't really want the default library creation process to include "make a stack template"

**Comment by soenkehahn** [comment]
@mgsloan: That makes a lot of sense. I've renamed it to `servant-0.4`. (There's already a `servant` template.)

**Comment by mgsloan** [comment]
Oops forgot to merge.  Thanks!

**Pull request merged**
