### PR TITLE
extra-source-files: README.md

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Travis asema to timeout

**Comment by bitemyapp** [comment]
Restarted

**Comment by phadej** [comment]
I guess travis just runs out of time. Either their build bots become slower or time bound got tighter, as I started experiencing time limit problems at work last week as well.

**Comment by bitemyapp** [comment]
Sigh, nuts.

**Comment by bitemyapp** [comment]
I'll merge this on the assumption maintainers don't mind, but please keep in mind stack-templates is just here to keep things working, I think they're trying to migrate off needing a centralized thingy.

**Pull request merged**
