### PR TITLE
Switch new-template to use hpack

### PR DESCRIPTION
**Pull request by snoyberg**

### CODE REVIEW

**Comment by mgsloan** [comment]
LGTM

**Comment by borsboom** [comment]
I'm a bit worried about this causing confusion (e.g. https://github.com/commercialhaskell/stack/issues/3539) for the more casual users of Stack.  There are probably a number of tutorials out there that use `stack new` and then talk about the .cabal file, for example.  I'm wondering if there's a way this change can be highlighted more, or maybe rolled out with a new version of Stack where we can announce it in the changelog?

**Comment by mgsloan** [comment]
That's a good point, hadn't considered that form of documentation.  Also, currently it can be confusing when you accidentally edit the cabal file instead of the hpack file - https://github.com/commercialhaskell/stack/issues/3383 - would be nice to have better messaging there.

Overall I'm in favor of the change, it makes sense to encourage people to learn how hpack works.

**Comment by borsboom** [comment]
I too am in favour of the change, but I do think it would be good to have https://github.com/commercialhaskell/stack/issues/3383 before we spring it on users who may not be expecting it.

**Comment by snoyberg** [comment]
I've added a comment to the Stack issue. I'll revert this change for now, and we can reinstate it once we resolve the issue in Stack.

**Comment by ashic** [comment]
Ouch.... I'd been preparing an introductory talk and had started in the interim. Re-running steps on a new project, and there's no hpack.... OMG OMG what do I do.... and then I see it chaged 8 days ago. Makes sense, but would be nice to have hpack as default soon.

**Comment by snoyberg** [comment]
If really desired, we could temporarily provide the new template under a different name (like `hpack-next`) and then your instructions could include `stack new foo hpack-next`.

**Comment by ashic** [comment]
I've switched to basic cabal with a note that hpack makes it easier. There's also simple-hpack, though it doesn't have tests, etc. A separate template could be useful, but if it's coming soon anyway... Whatever you guys think is best :)

**Pull request merged**
